CREATE TABLE IF NOT EXISTS halls
  (id SERIAL PRIMARY KEY, number_row
  SMALLINT NOT NULL, number_seat SMALLINT NOT NULL);

CREATE TABLE IF NOT EXISTS accounts
  (id INTEGER PRIMARY KEY REFERENCES halls(id), user_name
  VARCHAR(150) NOT NULL, phone_number VARCHAR(15) NOT NULL);