 CREATE TABLE IF NOT EXISTS CAR_BODY
 (
 	id SERIAL PRIMARY KEY,
 	body_name VARCHAR(40) NOT NULL
 ); 

 CREATE TABLE IF NOT EXISTS ENGINE
 (
 	id SERIAL PRIMARY KEY,
 	engine_name VARCHAR(40) NOT NULL
 ); 

 CREATE TABLE IF NOT EXISTS TRANSMISSION
 (
 	id SERIAL PRIMARY KEY,
 	trans_name VARCHAR(40) NOT NULL
 );

 CREATE TABLE IF NOT EXISTS CAR (
  	id SERIAL PRIMARY KEY,
  	model VARCHAR(40) NOT NULL,
  	car_body_id INTEGER NOT NULL,
  	engine_id INTEGER NOT NULL,
  	transmission_id INTEGER NOT NULL,
  	FOREIGN KEY(car_body_id) REFERENCES CAR_BODY (id),
  	FOREIGN KEY(engine_id) REFERENCES ENGINE (id),
  	FOREIGN KEY(transmission_id) REFERENCES TRANSMISSION (id)
 );